imagePullPolicy: IfNotPresent
backend:
  replicas: 2
  automountServiceAccountToken: true
frontend:
  replicas: 2
config:
  appEnv: production
  authMode: oidc
  storageBackend: gcs
secrets:
  provider: gcp
cloudSqlProxy:
  enabled: true
ingress:
  enabled: true
  className: gce
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "false"
