apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccountName }}
  labels: {{- include "dynamic-agentic.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.backend.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  labels: {{- include "dynamic-agentic.labels" . | nindent 4 }}
automountServiceAccountToken: false
